### ISSUE TITLE
In NumPy 2.0, `numpy.ComplexWarning` has been removed.

### ISSUE THREAD

**Issue by WarrenWeckesser** [b45ch1/algopy#58]
To work with NumPy 2.0, references to `numpy.ComplexWarning` must be changed to `numpy.exceptions.ComplexWarning`.  This appears to be the source of the problem reported in https://stackoverflow.com/questions/78712287/numpy-error-when-running-python-contract-from-algokit-framework/.

**Comment by b45ch1** [comment]
@WarrenWeckesser Thanks for the hint. I will have a look.

Please note that the issue on Stackoverflow is the result from a misunderstanding.
According to https://pypi.org/project/algorand-python/ the algorand-python library is imported via "import algopy". 
I suspect that the author of the Stackoverflow question ran "pip install algopy" instead of "pip install algorand-python".

**Comment by b45ch1** [comment]
new version supporting numpy 2.0.0 is available on Pypi https://pypi.org/project/algopy/0.7.1/

**Comment by b45ch1** [comment]
Closing ...
